spool startrekdic.txt

SET PAUSE OFF
COLUMN table_name FORMAT A20
COLUMN column_name FORMAT A20
COLUMN comments FORMAT A40 WRAPPED
SET LINESIZE 132

SELECT table_name, table_type, comments
FROM user_tab_comments
WHERE table_name IN ('PHOTOPROD','MSRMPROD''TELPROD','OBSERPROD','CUSTOMERORDER','CUSTOMERS','WORKORDER','WORKCENTER','PURCHASEORDER','PARTS','VENDOR','EMPLOYEE','PRODUCTS','PURCHASEPARTORDER','WORKORDERPARTS');
SELECT table_name, column_name, comments
FROM user_col_comments
WHERE table_name IN ('PHOTOPROD','MSRMPROD''TELPROD','OBSERPROD','CUSTOMERORDER','CUSTOMERS','WORKORDER','WORKCENTER','PURCHASEORDER','PARTS','VENDOR','EMPLOYEE','PRODUCTS','PURCHASEPARTORDER','WORKORDERPARTS');

spool off
